services:
  - type: web
    name: portfolio-rag-chatbot
    runtime: docker
    plan: free
    autoDeploy: false
    envVars:
      - key: PORT
        value: 8000

    dockerfilePath: Dockerfile
    dockerContext: .