import os
from dotenv import load_dotenv
load_dotenv()

GEMINI_API_KEY=os.getenv('GEMINI_API_KEY')
HUGGINGFACE_API_KEY=os.getenv('HUGGINGFACE_API_KEY')

# Embedding models
GEMINI_EMBEDDING_MODEL=os.getenv('GEMINI_EMBEDDING_MODEL')
BACKUP_EMBEDDING_MODEL=os.getenv('BACKUP_EMBEDDING_MODEL')
BACKUP_EMBEDDING_MODEL_REPO_ID=os.getenv('BACKUP_EMBEDDING_MODEL_REPO_ID')

# Text generation models
GEMINI_TEXT_GENERATION_MODEL=os.getenv('GEMINI_TEXT_GENERATION_MODEL')

COLLECTION_NAME=os.getenv('COLLECTION_NAME')
DB_PATH=os.getenv('DB_PATH')

DOCS_PATH=os.getenv('DOCS_PATH')